version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - target: 5672
        published: 5672
      - target: 15672
        published: 15672
    networks:
      - rabbit_bank_net

networks:
  rabbit_bank_net:
    driver: bridge
